project_id = "hbxswdfcuzgsihslhver"

[functions.transcribe-audio]
verify_jwt = true

[functions.generate-clips]
verify_jwt = true

[functions.render-clip]
verify_jwt = true

[functions.alchify-refiner-ai]
verify_jwt = true

[functions.render-creatomate]
verify_jwt = true